name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - 'latest'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - run: perl -V
      - run: perl -MPerl::Critic=critique -e "my @c = critique({-severity => 'harsh'}, shift); print @c ; exit (@c?1:0)" hello_world.pl
